name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MYSQL_HOST_PORT: 3800
      MYSQL_DATABASE: monarc_common
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: sqlmonarcuser
      MYSQL_PASSWORD: password

    steps:
    - uses: actions/checkout@v1

    #- name: Shutdown Ubuntu MySQL (SUDO)
      #run: sudo service mysql stop

    #- name: Start MariaDB and create databases
      #uses: getong/mariadb-action@v1.1
      #with:
        #host port: $MYSQL_HOST_PORT
        #mysql database: $MYSQL_DATABASE # Optional, default value is "test". The specified database which will be create
        #mysql root password: $MYSQL_ROOT_PASSWORD # Required if "mysql user" is empty, default is empty. The root superuser password
        #mysql user: $MYSQL_USER # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
        #mysql password: $MYSQL_PASSWORD # Required if "mysql user" exists. The password for the "mysql user"

    - name: Setup PHP
      uses: shivammathur/setup-php@v1
      with:
        php-version: '7.4'
        extensions: imagick, intl, xml, mysql #optional, setup extensions
        ini-values: post_max_size=256M, short_open_tag=On #optional, setup php.ini configuration
        coverage: xdebug #optional, setup coverage driver
        pecl: false #optional, setup PECL

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install PHP dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

 

    - name: Create monarc-zip 
      run: mkdir monarc-zip
    - name: zip module directory 
      uses: montudor/action-zip@v0.1.0
      with:
        args: zip -qq -r  ./monarc-zip/monarc-module.zip .
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: monarc
        path: monarc-zip

   
